{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d24682c-3006-4ade-a36f-b0a6002becca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: xlwt in /opt/app-root/lib/python3.8/site-packages (1.3.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: matplotlib in /opt/app-root/lib/python3.8/site-packages (3.7.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (1.0.7)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (9.5.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: importlib-resources>=3.2.0 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (5.4.0)\n",
      "Requirement already satisfied: numpy>=1.20 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (1.24.3)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (21.3)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (4.39.4)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (2.8.2)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (3.0.7)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /opt/app-root/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.6.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pycountry in /opt/app-root/lib/python3.8/site-packages (22.3.5)\n",
      "Requirement already satisfied: setuptools in /opt/app-root/lib/python3.8/site-packages (from pycountry) (62.0.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: python-dotenv in /opt/app-root/lib/python3.8/site-packages (1.0.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: boto3 in /opt/app-root/lib/python3.8/site-packages (1.26.135)\n",
      "Requirement already satisfied: botocore<1.30.0,>=1.29.135 in /opt/app-root/lib/python3.8/site-packages (from boto3) (1.29.135)\n",
      "Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/app-root/lib/python3.8/site-packages (from boto3) (0.6.1)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/app-root/lib/python3.8/site-packages (from boto3) (1.0.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/app-root/lib/python3.8/site-packages (from botocore<1.30.0,>=1.29.135->boto3) (1.26.9)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/app-root/lib/python3.8/site-packages (from botocore<1.30.0,>=1.29.135->boto3) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.135->boto3) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: trino in /opt/app-root/lib/python3.8/site-packages (0.324.0)\n",
      "Requirement already satisfied: sqlalchemy in /opt/app-root/lib/python3.8/site-packages (1.4.27)\n",
      "Requirement already satisfied: sqlalchemy-trino in /opt/app-root/lib/python3.8/site-packages (0.5.0)\n",
      "Requirement already satisfied: tzlocal in /opt/app-root/lib/python3.8/site-packages (from trino) (4.1)\n",
      "Requirement already satisfied: python-dateutil in /opt/app-root/lib/python3.8/site-packages (from trino) (2.8.2)\n",
      "Requirement already satisfied: requests in /opt/app-root/lib/python3.8/site-packages (from trino) (2.27.1)\n",
      "Requirement already satisfied: pytz in /opt/app-root/lib/python3.8/site-packages (from trino) (2022.1)\n",
      "Requirement already satisfied: backports.zoneinfo in /opt/app-root/lib/python3.8/site-packages (from trino) (0.2.1)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /opt/app-root/lib/python3.8/site-packages (from sqlalchemy) (1.1.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil->trino) (1.16.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests->trino) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests->trino) (2021.10.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from requests->trino) (2.0.12)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/app-root/lib/python3.8/site-packages (from requests->trino) (1.26.9)\n",
      "Requirement already satisfied: pytz-deprecation-shim in /opt/app-root/lib/python3.8/site-packages (from tzlocal->trino) (0.1.0.post0)\n",
      "Requirement already satisfied: tzdata in /opt/app-root/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal->trino) (2023.3)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (2.0.1)\n",
      "Requirement already satisfied: pyarrow in /opt/app-root/lib/python3.8/site-packages (12.0.0)\n",
      "Requirement already satisfied: fastparquet in /opt/app-root/lib/python3.8/site-packages (2023.4.0)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas) (1.24.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2022.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2023.3)\n",
      "Requirement already satisfied: fsspec in /opt/app-root/lib/python3.8/site-packages (from fastparquet) (2023.5.0)\n",
      "Requirement already satisfied: packaging in /opt/app-root/lib/python3.8/site-packages (from fastparquet) (21.3)\n",
      "Requirement already satisfied: cramjam>=2.3 in /opt/app-root/lib/python3.8/site-packages (from fastparquet) (2.6.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/app-root/lib/python3.8/site-packages (from packaging->fastparquet) (3.0.7)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: osc-ingest-tools in /opt/app-root/lib/python3.8/site-packages (0.4.3)\n",
      "Requirement already satisfied: boto3 in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (1.26.135)\n",
      "Requirement already satisfied: sqlalchemy in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (1.4.27)\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (2.0.1)\n",
      "Requirement already satisfied: python-dotenv in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (1.0.0)\n",
      "Requirement already satisfied: trino[sqlalchemy] in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (0.324.0)\n",
      "Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (0.6.1)\n",
      "Requirement already satisfied: botocore<1.30.0,>=1.29.135 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (1.29.135)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (1.0.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (2023.3)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (2022.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (1.24.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (2.8.2)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /opt/app-root/lib/python3.8/site-packages (from sqlalchemy->osc-ingest-tools) (1.1.2)\n",
      "Requirement already satisfied: requests in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]->osc-ingest-tools) (2.27.1)\n",
      "Requirement already satisfied: tzlocal in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]->osc-ingest-tools) (4.1)\n",
      "Requirement already satisfied: backports.zoneinfo in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]->osc-ingest-tools) (0.2.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/app-root/lib/python3.8/site-packages (from botocore<1.30.0,>=1.29.135->boto3->osc-ingest-tools) (1.26.9)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->osc-ingest-tools) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from requests->trino[sqlalchemy]->osc-ingest-tools) (2.0.12)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests->trino[sqlalchemy]->osc-ingest-tools) (2021.10.8)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests->trino[sqlalchemy]->osc-ingest-tools) (3.3)\n",
      "Requirement already satisfied: pytz-deprecation-shim in /opt/app-root/lib/python3.8/site-packages (from tzlocal->trino[sqlalchemy]->osc-ingest-tools) (0.1.0.post0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: openpyxl in /opt/app-root/lib/python3.8/site-packages (3.1.2)\n",
      "Requirement already satisfied: et-xmlfile in /opt/app-root/lib/python3.8/site-packages (from openpyxl) (1.1.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: country_converter in /opt/app-root/lib/python3.8/site-packages (1.0.0)\n",
      "Requirement already satisfied: pandas>=1.0 in /opt/app-root/lib/python3.8/site-packages (from country_converter) (2.0.1)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2022.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2023.3)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (1.24.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.0->country_converter) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pint_pandas in /opt/app-root/lib/python3.8/site-packages (0.3)\n",
      "Requirement already satisfied: pandas>=1.5 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas) (2.0.1)\n",
      "Requirement already satisfied: pint>=0.20.1 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas) (0.20.1)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2022.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (1.24.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2.8.2)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pint_pandas) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: openscm_units in /opt/app-root/lib/python3.8/site-packages (0.5.1)\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (from openscm_units) (2.0.1)\n",
      "Requirement already satisfied: pint in /opt/app-root/lib/python3.8/site-packages (from openscm_units) (0.20.1)\n",
      "Requirement already satisfied: globalwarmingpotentials in /opt/app-root/lib/python3.8/site-packages (from openscm_units) (0.9.3)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2022.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2023.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2.8.2)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (1.24.3)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->openscm_units) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
      "\u001b[31mERROR: Invalid requirement: 'pint=0.20.3'\n",
      "Hint: = is not a valid operator. Did you mean == ?\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# 'capture' magic prevents long outputs from spamming your notebook\n",
    "#%%capture pipoutput\n",
    "%pip install xlwt\n",
    "%pip install matplotlib\n",
    "%pip install pycountry\n",
    "# For loading predefined environment variables from files\n",
    "# Typically used to load sensitive access credentials\n",
    "%pip install python-dotenv\n",
    "\n",
    "# Standard python package for interacting with S3 buckets\n",
    "%pip install boto3\n",
    "\n",
    "# Interacting with Trino and using Trino with sqlalchemy\n",
    "%pip install trino sqlalchemy sqlalchemy-trino\n",
    "\n",
    "# Pandas and parquet file i/o\n",
    "%pip install pandas pyarrow fastparquet\n",
    "\n",
    "# OS-Climate utilities to make data ingest easier\n",
    "%pip install osc-ingest-tools\n",
    "#%pip install osc-ingest-trino\n",
    "%pip install openpyxl\n",
    "%pip install country_converter\n",
    "%pip install pint_pandas\n",
    "%pip install openscm_units\n",
    "%pip install pint=0.20.3\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d44cdf1e-b627-43b6-8e6e-9fc51879f2ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pint==0.20.1 in /opt/app-root/lib/python3.8/site-packages (0.20.1)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pint==0.20.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7159fa19-cdca-49df-8c73-d2c2150aba59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pint_pandas==0.3 in /opt/app-root/lib/python3.8/site-packages (0.3)\n",
      "Requirement already satisfied: pint>=0.20.1 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas==0.3) (0.20.1)\n",
      "Requirement already satisfied: pandas>=1.5 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas==0.3) (2.0.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (1.24.3)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2023.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2022.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pint_pandas==0.3) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pint_pandas==0.3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dc41d7e0-c36b-4f55-ad22-5a064dc9e685",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from openscm_units import unit_registry\n",
    "from pint import set_application_registry, Quantity\n",
    "from pint_pandas import PintArray, PintType\n",
    "# First we create the registry.\n",
    "ureg = unit_registry\n",
    "Q_ = ureg.Quantity\n",
    "ureg.default_format = '~'\n",
    "ureg.define(\"CO2e = CO2 = CO2eq\")\n",
    "ureg.define(\"USD = [currency] \")\n",
    "ureg.define(\"EUR = [currency_EUR] \")\n",
    "ureg.define('Millions=1000000')\n",
    "set_application_registry(ureg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e44fa75d-6d0b-4a42-ac66-ae5c67ee13b9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
