{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d24682c-3006-4ade-a36f-b0a6002becca",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting xlwt\n",
      "  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)\n",
      "\u001b[K     |████████████████████████████████| 99 kB 32.8 MB/s eta 0:00:01\n",
      "\u001b[?25hInstalling collected packages: xlwt\n",
      "Successfully installed xlwt-1.3.0\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: matplotlib in /opt/app-root/lib/python3.8/site-packages (3.4.2)\n",
      "Requirement already satisfied: numpy>=1.16 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (1.21.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (0.10.0)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (2.4.7)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (1.3.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (8.2.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/app-root/lib/python3.8/site-packages (from matplotlib) (2.8.1)\n",
      "Requirement already satisfied: six in /opt/app-root/lib/python3.8/site-packages (from cycler>=0.10->matplotlib) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting pycountry\n",
      "  Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)\n",
      "\u001b[K     |████████████████████████████████| 6.3 MB 23.1 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting importlib-resources>5.12.0\n",
      "  Downloading importlib_resources-6.4.0-py3-none-any.whl (38 kB)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /opt/app-root/lib/python3.8/site-packages (from importlib-resources>5.12.0->pycountry) (3.4.1)\n",
      "Installing collected packages: importlib-resources, pycountry\n",
      "Successfully installed importlib-resources-6.4.0 pycountry-24.6.1\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting python-dotenv\n",
      "  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)\n",
      "Installing collected packages: python-dotenv\n",
      "Successfully installed python-dotenv-1.0.1\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: boto3 in /opt/app-root/lib/python3.8/site-packages (1.17.11)\n",
      "Requirement already satisfied: botocore<1.21.0,>=1.20.11 in /opt/app-root/lib/python3.8/site-packages (from boto3) (1.20.101)\n",
      "Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/app-root/lib/python3.8/site-packages (from boto3) (0.10.0)\n",
      "Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/app-root/lib/python3.8/site-packages (from boto3) (0.3.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/app-root/lib/python3.8/site-packages (from botocore<1.21.0,>=1.20.11->boto3) (1.26.6)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/app-root/lib/python3.8/site-packages (from botocore<1.21.0,>=1.20.11->boto3) (2.8.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.11->boto3) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting trino\n",
      "  Downloading trino-0.329.0-py3-none-any.whl (53 kB)\n",
      "\u001b[K     |████████████████████████████████| 53 kB 19.8 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: sqlalchemy in /opt/app-root/lib/python3.8/site-packages (1.4.19)\n",
      "Collecting sqlalchemy-trino\n",
      "  Downloading sqlalchemy_trino-0.5.0-py3-none-any.whl (6.8 kB)\n",
      "Requirement already satisfied: tzlocal in /opt/app-root/lib/python3.8/site-packages (from trino) (2.1)\n",
      "Collecting backports.zoneinfo\n",
      "  Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)\n",
      "\u001b[K     |████████████████████████████████| 74 kB 99.7 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting requests>=2.31.0\n",
      "  Downloading requests-2.32.3-py3-none-any.whl (64 kB)\n",
      "\u001b[K     |████████████████████████████████| 64 kB 101.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pytz in /opt/app-root/lib/python3.8/site-packages (from trino) (2021.1)\n",
      "Requirement already satisfied: python-dateutil in /opt/app-root/lib/python3.8/site-packages (from trino) (2.8.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino) (2021.5.30)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino) (1.26.6)\n",
      "Collecting charset-normalizer<4,>=2\n",
      "  Downloading charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)\n",
      "\u001b[K     |████████████████████████████████| 141 kB 123.5 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: greenlet!=0.4.17 in /opt/app-root/lib/python3.8/site-packages (from sqlalchemy) (1.1.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil->trino) (1.16.0)\n",
      "Installing collected packages: charset-normalizer, requests, backports.zoneinfo, trino, sqlalchemy-trino\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.25.1\n",
      "    Uninstalling requests-2.25.1:\n",
      "      Successfully uninstalled requests-2.25.1\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "thoth-python 0.16.1 requires beautifulsoup4==4.6.3, but you have beautifulsoup4 4.9.3 which is incompatible.\u001b[0m\n",
      "Successfully installed backports.zoneinfo-0.2.1 charset-normalizer-3.3.2 requests-2.32.3 sqlalchemy-trino-0.5.0 trino-0.329.0\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (1.2.5)\n",
      "Requirement already satisfied: pyarrow in /opt/app-root/lib/python3.8/site-packages (4.0.1)\n",
      "Collecting fastparquet\n",
      "  Downloading fastparquet-2024.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.7 MB 23.7 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: numpy>=1.16.5 in /opt/app-root/lib/python3.8/site-packages (from pandas) (1.21.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2.8.1)\n",
      "Requirement already satisfied: pytz>=2017.3 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2021.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)\n",
      "Collecting pandas\n",
      "  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)\n",
      "\u001b[K     |████████████████████████████████| 12.4 MB 108.7 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting cramjam>=2.3\n",
      "  Downloading cramjam-2.8.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 2.0 MB 108.8 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: fsspec in /opt/app-root/lib/python3.8/site-packages (from fastparquet) (2021.6.1)\n",
      "Requirement already satisfied: packaging in /opt/app-root/lib/python3.8/site-packages (from fastparquet) (20.9)\n",
      "Collecting python-dateutil>=2.7.3\n",
      "  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n",
      "\u001b[K     |████████████████████████████████| 229 kB 130.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting tzdata>=2022.1\n",
      "  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)\n",
      "\u001b[K     |████████████████████████████████| 345 kB 126.0 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pyparsing>=2.0.2 in /opt/app-root/lib/python3.8/site-packages (from packaging->fastparquet) (2.4.7)\n",
      "Installing collected packages: tzdata, python-dateutil, pandas, cramjam, fastparquet\n",
      "  Attempting uninstall: python-dateutil\n",
      "    Found existing installation: python-dateutil 2.8.1\n",
      "    Uninstalling python-dateutil-2.8.1:\n",
      "      Successfully uninstalled python-dateutil-2.8.1\n",
      "  Attempting uninstall: pandas\n",
      "    Found existing installation: pandas 1.2.5\n",
      "    Uninstalling pandas-1.2.5:\n",
      "      Successfully uninstalled pandas-1.2.5\n",
      "Successfully installed cramjam-2.8.3 fastparquet-2024.2.0 pandas-2.0.3 python-dateutil-2.9.0.post0 tzdata-2024.1\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting osc-ingest-tools\n",
      "  Downloading osc_ingest_tools-0.5.2-py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: trino[sqlalchemy]>=0.323 in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (0.329.0)\n",
      "Collecting sqlalchemy>=2.0\n",
      "  Downloading SQLAlchemy-2.0.31-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 3.1 MB 38.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: boto3 in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (1.17.11)\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (2.0.3)\n",
      "Requirement already satisfied: python-dotenv in /opt/app-root/lib/python3.8/site-packages (from osc-ingest-tools) (1.0.1)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /opt/app-root/lib/python3.8/site-packages (from sqlalchemy>=2.0->osc-ingest-tools) (1.1.0)\n",
      "Collecting typing-extensions>=4.6.0\n",
      "  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)\n",
      "Requirement already satisfied: backports.zoneinfo in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]>=0.323->osc-ingest-tools) (0.2.1)\n",
      "Requirement already satisfied: requests>=2.31.0 in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]>=0.323->osc-ingest-tools) (2.32.3)\n",
      "Requirement already satisfied: pytz in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]>=0.323->osc-ingest-tools) (2021.1)\n",
      "Requirement already satisfied: tzlocal in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]>=0.323->osc-ingest-tools) (2.1)\n",
      "Requirement already satisfied: python-dateutil in /opt/app-root/lib/python3.8/site-packages (from trino[sqlalchemy]>=0.323->osc-ingest-tools) (2.9.0.post0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino[sqlalchemy]>=0.323->osc-ingest-tools) (2021.5.30)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino[sqlalchemy]>=0.323->osc-ingest-tools) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino[sqlalchemy]>=0.323->osc-ingest-tools) (1.26.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.31.0->trino[sqlalchemy]>=0.323->osc-ingest-tools) (3.3.2)\n",
      "Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (0.10.0)\n",
      "Requirement already satisfied: botocore<1.21.0,>=1.20.11 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (1.20.101)\n",
      "Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/app-root/lib/python3.8/site-packages (from boto3->osc-ingest-tools) (0.3.7)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil->trino[sqlalchemy]>=0.323->osc-ingest-tools) (1.16.0)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (1.21.0)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->osc-ingest-tools) (2024.1)\n",
      "Installing collected packages: typing-extensions, sqlalchemy, osc-ingest-tools\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing-extensions 3.10.0.0\n",
      "    Uninstalling typing-extensions-3.10.0.0:\n",
      "      Successfully uninstalled typing-extensions-3.10.0.0\n",
      "  Attempting uninstall: sqlalchemy\n",
      "    Found existing installation: SQLAlchemy 1.4.19\n",
      "    Uninstalling SQLAlchemy-1.4.19:\n",
      "      Successfully uninstalled SQLAlchemy-1.4.19\n",
      "Successfully installed osc-ingest-tools-0.5.2 sqlalchemy-2.0.31 typing-extensions-4.12.2\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting openpyxl\n",
      "  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)\n",
      "\u001b[K     |████████████████████████████████| 250 kB 27.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting et-xmlfile\n",
      "  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)\n",
      "Installing collected packages: et-xmlfile, openpyxl\n",
      "Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting country_converter\n",
      "  Downloading country_converter-1.2-py3-none-any.whl (45 kB)\n",
      "\u001b[K     |████████████████████████████████| 45 kB 26.0 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pandas>=1.0 in /opt/app-root/lib/python3.8/site-packages (from country_converter) (2.0.3)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (1.21.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2021.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.0->country_converter) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.0->country_converter) (1.16.0)\n",
      "Installing collected packages: country-converter\n",
      "Successfully installed country-converter-1.2\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting pint_pandas\n",
      "  Downloading Pint_Pandas-0.3-py2.py3-none-any.whl (23 kB)\n",
      "Collecting pint>=0.20.1\n",
      "  Downloading Pint-0.21.1-py3-none-any.whl (290 kB)\n",
      "\u001b[K     |████████████████████████████████| 290 kB 38.0 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pandas>=1.5 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas) (2.0.3)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2021.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2024.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas) (1.21.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pint_pandas) (1.16.0)\n",
      "Installing collected packages: pint, pint-pandas\n",
      "Successfully installed pint-0.21.1 pint-pandas-0.3\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting openscm_units\n",
      "  Downloading openscm_units-0.5.2-py2.py3-none-any.whl (13 kB)\n",
      "Collecting globalwarmingpotentials\n",
      "  Downloading globalwarmingpotentials-0.11.1-py2.py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: pandas in /opt/app-root/lib/python3.8/site-packages (from openscm_units) (2.0.3)\n",
      "Requirement already satisfied: pint in /opt/app-root/lib/python3.8/site-packages (from openscm_units) (0.21.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2024.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (1.21.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2021.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas->openscm_units) (2.9.0.post0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->openscm_units) (1.16.0)\n",
      "Installing collected packages: globalwarmingpotentials, openscm-units\n",
      "Successfully installed globalwarmingpotentials-0.11.1 openscm-units-0.5.2\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pint in /opt/app-root/lib/python3.8/site-packages (0.21.1)\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: tzlocal in /opt/app-root/lib/python3.8/site-packages (2.1)\n",
      "Collecting tzlocal\n",
      "  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)\n",
      "Requirement already satisfied: backports.zoneinfo in /opt/app-root/lib/python3.8/site-packages (from tzlocal) (0.2.1)\n",
      "Installing collected packages: tzlocal\n",
      "  Attempting uninstall: tzlocal\n",
      "    Found existing installation: tzlocal 2.1\n",
      "    Uninstalling tzlocal-2.1:\n",
      "      Successfully uninstalled tzlocal-2.1\n",
      "Successfully installed tzlocal-5.2\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# 'capture' magic prevents long outputs from spamming your notebook\n",
    "#%%capture pipoutput\n",
    "%pip install xlwt\n",
    "%pip install matplotlib\n",
    "%pip install pycountry\n",
    "# For loading predefined environment variables from files\n",
    "# Typically used to load sensitive access credentials\n",
    "%pip install python-dotenv\n",
    "\n",
    "# Standard python package for interacting with S3 buckets\n",
    "%pip install boto3\n",
    "\n",
    "# Interacting with Trino and using Trino with sqlalchemy\n",
    "%pip install trino sqlalchemy sqlalchemy-trino\n",
    "\n",
    "# Pandas and parquet file i/o\n",
    "%pip install pandas pyarrow fastparquet\n",
    "\n",
    "# OS-Climate utilities to make data ingest easier\n",
    "%pip install osc-ingest-tools\n",
    "#%pip install osc-ingest-trino\n",
    "%pip install openpyxl\n",
    "%pip install country_converter\n",
    "%pip install pint_pandas\n",
    "%pip install openscm_units\n",
    "%pip install pint\n",
    "%pip install --upgrade tzlocal\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d44cdf1e-b627-43b6-8e6e-9fc51879f2ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pint==0.20.1\n",
      "  Downloading Pint-0.20.1-py3-none-any.whl (269 kB)\n",
      "\u001b[K     |████████████████████████████████| 269 kB 22.9 MB/s eta 0:00:01\n",
      "\u001b[?25hInstalling collected packages: pint\n",
      "  Attempting uninstall: pint\n",
      "    Found existing installation: Pint 0.21.1\n",
      "    Uninstalling Pint-0.21.1:\n",
      "      Successfully uninstalled Pint-0.21.1\n",
      "Successfully installed pint-0.20.1\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pint==0.20.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7159fa19-cdca-49df-8c73-d2c2150aba59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pint_pandas==0.3 in /opt/app-root/lib/python3.8/site-packages (0.3)\n",
      "Requirement already satisfied: pandas>=1.5 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas==0.3) (2.0.3)\n",
      "Requirement already satisfied: pint>=0.20.1 in /opt/app-root/lib/python3.8/site-packages (from pint_pandas==0.3) (0.20.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2021.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (2024.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in /opt/app-root/lib/python3.8/site-packages (from pandas>=1.5->pint_pandas==0.3) (1.21.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pint_pandas==0.3) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 21.1.3; however, version 24.1.2 is available.\n",
      "You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pint_pandas==0.3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dc41d7e0-c36b-4f55-ad22-5a064dc9e685",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from openscm_units import unit_registry\n",
    "from pint import set_application_registry, Quantity\n",
    "from pint_pandas import PintArray, PintType\n",
    "# First we create the registry.\n",
    "ureg = unit_registry\n",
    "Q_ = ureg.Quantity\n",
    "ureg.default_format = '~'\n",
    "ureg.define(\"CO2e = CO2 = CO2eq\")\n",
    "ureg.define(\"USD = [currency] \")\n",
    "ureg.define(\"EUR = [currency_EUR] \")\n",
    "ureg.define('Millions=1000000')\n",
    "set_application_registry(ureg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e44fa75d-6d0b-4a42-ac66-ae5c67ee13b9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
